name: autopublish production

on:
  pull_request:
    branches: [deploy-prod]
  push:
    branches: [deploy-prod]

jobs:
  checks:
    if: github.event_name !='push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Deploy
        run: |
            if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
            elif [ -e package-lock.json ]; then
            npm ci
            else
            npm i
            fi
            npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email "so010410@naver.com"
          git config --global user.name "green-study"
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npx docusaurus build
          echo "docs.robolink.com" >./build/CNAME
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DOCS_PROD_HOST }}
          username: ${{ secrets.DOCS_PROD_USERNAME }}
          port: ${{ secrets.DOCS_PROD_SSH_PORT }}
          key: ${{ secrets.DOCS_PROD_SSH_KEY }}
          source: "./build/*"
          target: "/var/www/docs.robolink.com"
          strip_components: 1
